version: '3.8'

services:
  postgres:
    build: ./db
    environment:
      POSTGRES_DB: viatabloid
      POSTGRES_USER: viatabloiduser
      POSTGRES_PASSWORD: viatabloidpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/viatabloid
      SPRING_DATASOURCE_USERNAME: viatabloiduser
      SPRING_DATASOURCE_PASSWORD: viatabloidpassword

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  postgres-data: